name: Run all tests

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Chaeckout repositoru
        uses: actions/checkout@v3
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - name: Test with dotnet
        run: dotnet test
